package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* Monday, 20 November 2023 14:56:39 o'clock GMT+01:00
*/

public interface IConversionRemoteOperations 
{
  double conversionMontant (float mt);
} // interface IConversionRemoteOperations
